### ISSUE TITLE
0.9.5 not released

### ISSUE THREAD

**Issue by svoop** [opahk/banking_data#16]
Thank you for considering cutting a release of 0.9.5, the current release on Rubygems is not compatible with Ruby 3 due to the outdated smarter_csv dependency.

**Comment by svoop** [comment]
@opahk Ping! Sorry to insist, but this is blocking us from going Ruby 3 and since this gem is pulled by a gem required by a vendored gem, I can't easily switch to unreleased code from the repo. Thanks for taking a look! /cc @TPei @schasse

**Comment by TPei** [comment]
Hey @svoop thanks for reaching out. I'll look into it :)

**Comment by schasse** [comment]
0.9.5 released.

**Comment by svoop** [comment]
Thanks a bunch, saves the day!!
